[package]
name = "xs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
cacache = "13"
fjall = "0.6.5"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
scru128 = { version = "3", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssri = "9.2.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
static_assertions = "1.1.0"
temp-dir = "0.1.13"
